version: 2

models:
  - name: stg_customer
    description: >
      Staging table for customer data from TPCH.
      This model cleans column names and provides a consistent interface for downstream models.
    columns:
      - name: customer_key
        description: Unique identifier for each customer
        tests:
          - unique
          - not_null
      - name: customer_name
        description: Name of the customer
        tests:
          - not_null
      - name: customer_address
        description: Customer's address
      - name: nation_key
        description: Foreign key to nation table
        tests:
          - not_null
      - name: phone_number
        description: Customer's phone number
      - name: account_balance
        description: Customer's account balance
      - name: market_segment
        description: Market segment the customer belongs to
      - name: comment
        description: Additional comments about the customer

  - name: stg_orders
    description: >
      Staging table for orders data from TPCH.
      This model cleans column names and provides a consistent interface for downstream models.
    columns:
      - name: order_key
        description: Unique identifier for each order
        tests:
          - unique
          - not_null
      - name: customer_key
        description: Foreign key to customer table
        tests:
          - not_null
      - name: order_status
        description: Status of the order (e.g., F, O, P)
      - name: total_price
        description: Total price of the order
      - name: order_date
        description: Date the order was placed
        tests:
          - not_null
      - name: order_priority
        description: Priority level of the order
      - name: clerk
        description: Clerk who processed the order
      - name: ship_priority
        description: Shipping priority
      - name: comment
        description: Additional comments about the order

  - name: stg_lineitem
    description: >
      Staging table for line item data from TPCH.
      This model cleans column names and provides a consistent interface for downstream models.
    columns:
      - name: order_key
        description: Foreign key to orders table
        tests:
          - not_null
      - name: part_key
        description: Foreign key to part table
        tests:
          - not_null
      - name: supplier_key
        description: Foreign key to supplier table
        tests:
          - not_null
      - name: line_number
        description: Line number within the order
        tests:
          - not_null
      - name: quantity
        description: Quantity of items
      - name: extended_price
        description: Extended price (quantity * price)
      - name: discount
        description: Discount applied
      - name: tax
        description: Tax applied
      - name: return_flag
        description: Return flag status
      - name: line_status
        description: Line item status
      - name: ship_date
        description: Date the item was shipped
      - name: commit_date
        description: Committed delivery date
      - name: receipt_date
        description: Date the item was received
      - name: ship_instructions
        description: Shipping instructions
      - name: ship_mode
        description: Mode of shipping
      - name: comment
        description: Additional comments about the line item

  - name: stg_nation
    description: >
      Staging table for nation data from TPCH.
      This model cleans column names and provides a consistent interface for downstream models.
    columns:
      - name: nation_key
        description: Unique identifier for each nation
        tests:
          - unique
          - not_null
      - name: nation_name
        description: Name of the nation
        tests:
          - not_null
      - name: region_key
        description: Foreign key to region table
        tests:
          - not_null
      - name: comment
        description: Additional comments about the nation

